### ISSUE TITLE
SDR++ Server Support

### ISSUE THREAD

**Issue by ChrisDev8** [Sultan-papagani/sdrpp_new_rtlsdr_source#3]
Whenever I use it with SDR++ Server it crashes. I've also made sure both the server and client have the module enable and working, but it still doesn't work. This would be amazing because the SDR++ Server is the best server since it fast and responsive. And having more advanced controls makes the experience even better.

**Comment by Sultan-papagani** [comment]
use my newer source https://github.com/Sultan-papagani/sdrpp_rtlsdr_source 
it supports sdr++ server. just follow the instructions for sdr++ server, Thanks!
