### ISSUE TITLE
Problem with 20240422 Release of SDR++

### ISSUE THREAD

**Issue by WB0OCV** [Sultan-papagani/sdrpp_new_rtlsdr_source#4]
The alternative set of dlls provided by Sultan-papgani that allow for additional AGC and gain settings for the RTL-SDR Blog V4 have worked with past versions of SDR++, but with the latest release of SDR++ on 20240422, the modified dll (new_rtl_sdr_source.dll) causes the program to hang when launching the program in a folder from a prior installation.  If one deletes the json files, the program will start, but the new_rtl_sdr module isn't recognized.  If one tries to create the new module, the program crashes.  I just wanted to make you aware of this issue.  Thank you for such a wonderful enhanced set of dlls.  
Ken -- WBØOCV

**Comment by Sultan-papagani** [comment]
yeah this repo is old 🤷‍♂️ use my newer  [source](https://github.com/Sultan-papagani/sdrpp_rtlsdr_source) and delete the old one (for compatibility)

Thank you very much! <3

**Comment by WB0OCV** [comment]
Greetings,
Im still seeing the same behavior with the two most recent updates to SDR++, and both the old and new versions of the modified dlls. Both cause SDR++ to crash when trying ot install the new module.
One other thing I noticed is that the Zip-file for the new version does not contain the rtlsdr.dll file that the old Zip-file did. The instructions state to: "...Replace the rtlsdr.dll with the "librtlsdr.dll".  Do you mean to just copy the librtlsdr.dll into the root folder and delete the rtlsdr.dll file, or to copy the librtlsdr.dll into the root folder and remane it to rtlsdr.dll?  I'm a bit confused on what exactly you mean by "**_Replace_** the rtlsdr.dll with the "librtlsdr.dll"
Thank you and 73
Ken -- WBØOCV

**Comment by Sultan-papagani** [comment]
i fixed the new(er) source, and no there is no renaming, just put the librtlsdr.dll to the same folder (you can delete the old rtlsdr.dll)
